---
# Main tasks for Elasticsearch role

# Include OS-specific variables
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: elasticsearch

# Include version-specific variable overrides
- name: Include version-specific variables
  include_vars: "{{ elasticsearch_version_major }}.yml"
  when: elasticsearch_version_major is defined
  ignore_errors: yes
  tags: elasticsearch

# VM preparation tasks
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: elasticsearch

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  tags: elasticsearch

# Elasticsearch GPG key and repository setup
- name: Download Elasticsearch GPG key
  shell: >
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | 
    sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg
  tags: elasticsearch

- name: Add Elastic repository
  shell: >
    echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] 
    https://artifacts.elastic.co/packages/{{ elasticsearch_version_major }}.x/apt stable main" | 
    sudo tee /etc/apt/sources.list.d/elastic-{{ elasticsearch_version_major }}.x.list
  args:
    creates: /etc/apt/sources.list.d/elastic-{{ elasticsearch_version_major }}.x.list
  tags: elasticsearch

- name: Update apt cache after adding repository
  apt:
    update_cache: yes
  tags: elasticsearch

# Install Elasticsearch
- name: Install Elasticsearch
  apt:
    name: "elasticsearch{% if elasticsearch_version is defined and elasticsearch_version != 'latest' %}={{ elasticsearch_version }}{% endif %}"
    state: present
  register: elasticsearch_install
  tags: elasticsearch

# Create data directory if specified
- name: Create custom data directory
  file:
    path: "{{ elasticsearch_data_path }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0750'
  when: elasticsearch_data_path != "/var/lib/elasticsearch"
  tags: elasticsearch

# Ensure the hardcoded data directory exists
- name: Ensure /mnt/data/elasticsearch directory exists with proper permissions
  file:
    path: /mnt/data/elasticsearch
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0750'
    recurse: yes
  tags:
    - elasticsearch
    - elasticsearch:config

# Backup original configuration
- name: Backup original Elasticsearch configuration
  copy:
    src: /etc/elasticsearch/elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml.backup
    remote_src: yes
    force: no
  ignore_errors: yes
  when: elasticsearch_install.changed
  tags: elasticsearch

# Update Elasticsearch configuration directly 
- name: Update Elasticsearch configuration directly
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^(#)?network\.host:.*', line: 'network.host: 0.0.0.0' }
    - { regexp: '^(#)?cluster\.name:.*', line: 'cluster.name: es-poc' }
    - { regexp: '^(#)?path\.data:.*', line: 'path.data: /mnt/data/elasticsearch' }
  tags:
    - elasticsearch
    - elasticsearch:config

# Enable and start service
- name: Reload systemd
  systemd:
    daemon_reload: yes
  tags: elasticsearch

- name: Enable Elasticsearch service
  systemd:
    name: elasticsearch.service
    enabled: yes
  tags: elasticsearch

- name: Start Elasticsearch service
  systemd:
    name: elasticsearch.service
    state: started
  tags: elasticsearch
