---
# Main tasks for Elasticsearch role

# Include OS-specific variables
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: elasticsearch

# Include version-specific variable overrides
- name: Include version-specific variables
  include_vars: "{{ elasticsearch_version_major }}.yml"
  when: elasticsearch_version_major is defined
  ignore_errors: yes
  tags: elasticsearch

# VM preparation tasks
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: elasticsearch

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  tags: elasticsearch

# Elasticsearch GPG key and repository setup
- name: Download Elasticsearch GPG key
  shell: >
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | 
    sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg
  tags: elasticsearch

- name: Add Elastic repository
  shell: >
    echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] 
    https://artifacts.elastic.co/packages/{{ elasticsearch_version_major }}.x/apt stable main" | 
    sudo tee /etc/apt/sources.list.d/elastic-{{ elasticsearch_version_major }}.x.list
  args:
    creates: /etc/apt/sources.list.d/elastic-{{ elasticsearch_version_major }}.x.list
  tags: elasticsearch

- name: Update apt cache after adding repository
  apt:
    update_cache: yes
  tags: elasticsearch

# Install Elasticsearch
- name: Install Elasticsearch
  apt:
    name: "elasticsearch{% if elasticsearch_version is defined and elasticsearch_version != 'latest' %}={{ elasticsearch_version }}{% endif %}"
    state: present
  register: elasticsearch_install
  tags: elasticsearch

# Create data directory if specified
- name: Create custom data directory
  file:
    path: "{{ elasticsearch_data_path }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0750'
  when: elasticsearch_data_path != "/var/lib/elasticsearch"
  tags: elasticsearch

# Ensure the hardcoded data directory exists
- name: Ensure /mnt/data/elasticsearch directory exists with proper permissions
  file:
    path: /mnt/data/elasticsearch
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0750'
    recurse: yes
  tags:
    - elasticsearch
    - elasticsearch:config

# Backup original configuration
- name: Backup original Elasticsearch configuration
  copy:
    src: /etc/elasticsearch/elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml.backup
    remote_src: yes
    force: no
  ignore_errors: yes
  when: elasticsearch_install.changed
  tags: elasticsearch

# Update Elasticsearch configuration directly 
- name: Update Elasticsearch configuration directly
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^(#)?network\.host:.*', line: 'network.host: 0.0.0.0' }
    - { regexp: '^(#)?cluster\.name:.*', line: 'cluster.name: es-poc' }
    - { regexp: '^(#)?path\.data:.*', line: 'path.data: /mnt/data/elasticsearch' }
  tags:
    - elasticsearch
    - elasticsearch:config

# Enable and start service
- name: Reload systemd
  systemd:
    daemon_reload: yes
  tags: elasticsearch

- name: Enable Elasticsearch service
  systemd:
    name: elasticsearch.service
    enabled: yes
  when: "'elasticsearch_master' in group_names"
  tags: elasticsearch

- name: Start Elasticsearch service
  systemd:
    name: elasticsearch.service
    state: started
  when: "'elasticsearch_master' in group_names"
  tags: elasticsearch

# Enrollment token handling - Master node
- name: Generate node enrollment token on master node
  shell: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s node
  register: enrollment_token
  when: 
    - "'elasticsearch_master' in group_names"
    - elasticsearch_version_major | int >= 8
  tags:
    - elasticsearch
    - elasticsearch:enrollment

- name: Print enrollment token
  debug:
    msg: "Enrollment token: {{ enrollment_token.stdout }}"
  when: 
    - "'elasticsearch_master' in group_names"
    - elasticsearch_version_major | int >= 8
    - enrollment_token is defined
  tags:
    - elasticsearch
    - elasticsearch:enrollment

# Register the token as a fact so it can be used by other hosts
- name: Set enrollment token as a fact
  set_fact:
    node_enrollment_token: "{{ enrollment_token.stdout }}"
  when: 
    - enrollment_token is defined
    - enrollment_token.stdout is defined
  tags:
    - elasticsearch
    - elasticsearch:enrollment

# Share the token with all hosts in the play
- name: Share enrollment token with all hosts
  set_fact:
    node_enrollment_token: "{{ hostvars[groups['elasticsearch_master'][0]]['node_enrollment_token'] }}"
  when:
    - "'elasticsearch_master' in groups"
    - groups['elasticsearch_master'] | length > 0
    - hostvars[groups['elasticsearch_master'][0]]['node_enrollment_token'] is defined
  tags:
    - elasticsearch
    - elasticsearch:enrollment

# Create a temporary token file on data nodes
- name: Create token file on data nodes
  copy:
    content: "{{ node_enrollment_token }}"
    dest: "/tmp/es_enrollment_token.txt"
    mode: '0600'
    owner: elasticsearch
    group: elasticsearch
  when: 
    - "'elasticsearch_data' in group_names"
    - "'elasticsearch_master' not in group_names"
    - elasticsearch_version_major | int >= 8
    - node_enrollment_token is defined
  tags:
    - elasticsearch
    - elasticsearch:enrollment

# Enroll data nodes to the cluster
- name: Register data nodes to elasticsearch cluster
  shell: |
    echo "y" | /usr/share/elasticsearch/bin/elasticsearch-reconfigure-node --enrollment-token $(cat /tmp/es_enrollment_token.txt)
  register: enrollment_result
  when:
    - "'elasticsearch_data' in group_names"
    - "'elasticsearch_master' not in group_names"
    - elasticsearch_version_major | int >= 8
    - node_enrollment_token is defined
  failed_when: enrollment_result.rc != 0 and "Node is already enrolled in a cluster" not in enrollment_result.stderr
  tags:
    - elasticsearch
    - elasticsearch:enrollment

# Clean up enrollment token files
- name: Remove enrollment token files
  file:
    path: "/tmp/es_enrollment_token.txt"
    state: absent
  when: node_enrollment_token is defined
  tags:
    - elasticsearch
    - elasticsearch:enrollment
