---
# Handlers for Elasticsearch

- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: yes

- name: reload elasticsearch
  systemd:
    name: elasticsearch
    state: reloaded

- name: restart elasticsearch cluster rolling
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin list | grep -q {{ item }} || echo "Plugin {{ item }} not installed"
  args:
    executable: /bin/bash
  with_items: "{{ elasticsearch_plugins | default([]) }}"
  notify: restart elasticsearch