---
# Debian/Ubuntu specific variables for Elasticsearch

elasticsearch_user: elasticsearch
elasticsearch_group: elasticsearch
elasticsearch_package_name: elasticsearch
elasticsearch_service_name: elasticsearch
elasticsearch_conf_dir: /etc/elasticsearch