---
# Default variables for Elasticsearch role

# Version settings
elasticsearch_version: "latest"
elasticsearch_version_major: "8"

# Network settings
elasticsearch_bind_host: "0.0.0.0"
elasticsearch_http_port: 9200

# Cluster settings
elasticsearch_cluster_name: "es-poc"
elasticsearch_node_name: "{{ inventory_hostname }}"
elasticsearch_node_roles: ["master", "data", "ingest"]

# Path settings
elasticsearch_data_path: "/mnt/data/elasticsearch"
elasticsearch_logs_path: "/var/log/elasticsearch"

# JVM settings
elasticsearch_heap_size: "1g"

# Discovery settings for multi-node clusters
elasticsearch_discovery_seed_hosts: ["127.0.0.1"]
elasticsearch_initial_master_nodes: ["{{ inventory_hostname }}"]

# Security settings
elasticsearch_security_enabled: true

# System settings
elasticsearch_bootstrap_memory_lock: false