---
# Simple playbook for installing Elasticsearch on all elastic nodes

- name: Install and configure Elasticsearch nodes
  hosts: elasticsearch
  become: yes
  roles:
    - elasticsearch
  tags:
    - elasticsearch

- name: Install and configure Kibana on master nodes
  hosts: elasticsearch_master
  become: yes
  roles:
    - kibana
  tags:
    - kibana

- name: Display ELK Stack credentials and access information
  hosts: elasticsearch_master
  become: yes
  gather_facts: yes
  tasks:
    - name: Get Elasticsearch credentials from master node
      shell: cat /etc/elasticsearch/elastic_credentials.txt || echo "Password not found in file"
      register: elastic_stored_credentials
      changed_when: false
      
    - name: Set credential facts
      set_fact:
        es_password: "{{ elastic_stored_credentials.stdout | default('Password not found') }}"
        es_master_ip: "{{ ansible_host }}"
        es_internal_ip: "{{ ansible_default_ipv4.address }}"
        
    - name: Format data nodes list
      set_fact:
        data_nodes_list: "{% for host in groups['elasticsearch_data'] %}  - {{ host }} ({{ hostvars[host].elasticsearch_node_role | default('data') }}){% endfor %}"

    # Directly output the summary using debug module with no quotes
    - name: Create a multiline string with summary information
      set_fact:
        summary_text: |
          ===========================================================
                          ELK STACK DEPLOYMENT SUMMARY                
          ===========================================================
          Elasticsearch cluster name: es-poc
          Elasticsearch endpoint: https://{{ es_master_ip }}:9200
          Kibana URL: http://{{ es_master_ip }}:5601
          Username: elastic
          Password: {{ es_password }}
          ===========================================================
          Elasticsearch data nodes:
          {{ data_nodes_list }}
          ===========================================================
          Credentials are stored at: /etc/elasticsearch/elastic_credentials.txt
          ===========================================================
          Note: For internal network access (if using VPN):
          Internal Elasticsearch API: https://{{ es_internal_ip }}:9200
          Internal Kibana UI: http://{{ es_internal_ip }}:5601
          ===========================================================
      delegate_to: localhost
      run_once: true
      
    - name: Display summary (without quotes)
      debug:
        msg: "{{ summary_text }}"
      delegate_to: localhost
      run_once: true