---
# Simple playbook for installing Elasticsearch on all elastic nodes

- name: Install and configure Elasticsearch nodes
  hosts: elasticsearch
  become: yes
  roles:
    - elasticsearch
  tags:
    - elasticsearch

- name: Install and configure Kibana on master nodes
  hosts: elasticsearch_master
  become: yes
  roles:
    - kibana
  tags:
    - kibana