---
# Simple playbook for installing Elasticsearch on all elastic nodes

- name: Install and configure Elasticsearch nodes
  hosts: elasticsearch
  become: yes
  roles:
    - elasticsearch
  tags:
    - elasticsearch

- name: Install and configure Kibana on master nodes
  hosts: elasticsearch_master
  become: yes
  roles:
    - kibana
  tags:
    - kibana

- name: Display ELK Stack credentials and access information
  hosts: elasticsearch_master
  become: yes  # Changed to yes to ensure we can read credential files
  gather_facts: yes
  tasks:
    - name: Get Elasticsearch credentials from master node
      shell: cat /etc/elasticsearch/elastic_credentials.txt || echo "Password not found in file"
      register: elastic_stored_credentials
      changed_when: false
      
    - name: Set credential facts
      set_fact:
        es_password: "{{ elastic_stored_credentials.stdout | default('Password not found') }}"
        es_master_ip: "{{ ansible_host }}"
        es_internal_ip: "{{ ansible_default_ipv4.address }}"
      
    - name: Display ELK Stack Summary
      debug:
        msg:
          - "==========================================================="
          - "                ELK STACK DEPLOYMENT SUMMARY                "
          - "==========================================================="
          - "Elasticsearch cluster name: es-poc"
          - "Elasticsearch endpoint: https://{{ es_master_ip }}:9200"
          - "Kibana URL: http://{{ es_master_ip }}:5601"
          - "Username: elastic"
          - "Password: {{ es_password }}"
          - "==========================================================="
          - "Elasticsearch data nodes:"
          - "{% for host in groups['elasticsearch_data'] %}  - {{ host }} ({{ hostvars[host].elasticsearch_node_role | default('data') }}){% endfor %}"
          - "==========================================================="
          - "Credentials are stored at: /etc/elasticsearch/elastic_credentials.txt"
          - "==========================================================="
          - "Note: For internal network access (if using VPN):"  
          - "Internal Elasticsearch API: https://{{ es_internal_ip }}:9200"
          - "Internal Kibana UI: http://{{ es_internal_ip }}:5601"
          - "==========================================================="
      delegate_to: localhost
      run_once: true