---
# Handlers for Kibana role

- name: restart kibana
  systemd:
    name: kibana
    state: restarted
  listen: restart kibana

- name: kibana started
  debug:
    msg: "Kibana service has been started. Access at http://{{ inventory_hostname }}:{{ kibana_port }}"