---
# Handlers for Kibana

- name: restart kibana
  systemd:
    name: kibana
    state: restarted
    daemon_reload: yes

- name: kibana started
  debug:
    msg: "Kibana service has been started. Access at http://{{ inventory_hostname }}:{{ kibana_port }}"